# DEFAULT
spring:
  profiles:
    active: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
---
# DEV
spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
